"use client";

import { useState } from "react";

export default function SummarizerButton({ bidId, isPro }: { bidId: string; isPro: boolean }) {
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleSummarize = async () => {
    if (!isPro) {
      alert("AI Summarizer is a Business Pro feature. Please upgrade to unlock.");
      return;
    }

    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/bids/summarize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ bidId })
      });
      const data = await res.json();
      if (data.success) {
        setSummary(data.summary);
      } else {
        setError(data.error);
      }
    } catch (e) {
      setError("An error occurred");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mt-8 mb-10">
      {!summary ? (
        <button
          onClick={handleSummarize}
          disabled={loading}
          className="flex items-center gap-3 bg-gradient-to-br from-indigo-600 to-blue-600 text-white px-6 py-3 rounded-2xl font-bold shadow-lg shadow-indigo-200 hover:-translate-y-1 transition-all disabled:opacity-50"
        >
          {loading ? (
            <>
              <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
              Summarizing...
            </>
          ) : (
            <>
              <span className="text-xl">✨</span>
              AI Summarize Tender
              {!isPro && (
                <span className="bg-white/20 text-[10px] uppercase px-1.5 py-0.5 rounded flex items-center gap-1">
                  <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
                  PRO
                </span>
              )}
            </>
          )}
        </button>
      ) : (
        <div className="bg-indigo-50 border border-indigo-100 rounded-3xl p-8 relative overflow-hidden animate-in fade-in slide-in-from-top-4 duration-500">
          <div className="absolute top-0 right-0 p-4">
             <button onClick={() => setSummary(null)} className="text-slate-400 hover:text-slate-600">
               <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
             </button>
          </div>
          <h3 className="text-indigo-900 font-bold mb-4 flex items-center gap-2">
            <span className="text-xl">✨</span>
            AI Tender Summary
          </h3>
          <div className="prose prose-indigo prose-sm max-w-none text-indigo-900/80 leading-relaxed">
            {summary.split("\n").map((line, i) => (
              <p key={i}>{line}</p>
            ))}
          </div>
          <div className="mt-6 flex items-center gap-2 text-[10px] text-indigo-400 font-bold uppercase tracking-widest">
            Generated by Gemini AI
          </div>
        </div>
      )}
      {error && <p className="mt-2 text-red-500 text-sm font-bold ml-2">❌ {error}</p>}
    </div>
  );
}
